// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState,useEffect} from "react";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
//import "../sass/circularprogressbars.scss";
import { useNavigate } from 'react-router-dom'
//import Web3 from 'web3'
//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

function VerifyLink_(props) {

//const [pageparamsState, setpageparamsState] = useState({ address: "" })

const [addressCheck, setaddressCheck] = useState({result: false})
/*    
const connectWalletandcheck = (address) => {

    console.log("Reached wallet",window.ethereum)
    if (window.ethereum) {
            
            const ethereum = window.ethereum;
            
           let web3 = new Web3(ethereum);
           
        
        ethereum.enable().then((accounts) => {
            let account = accounts[0];
             
            if(account == address)
            {
            setaddressCheck(prevState => {
                return {
                  ...prevState,
                  result: true
                }
              })
            }

        })
    }
}
*/


  useEffect(() => {
    props.urlParser();
    //connectWalletandcheck(props.allUrlParams.address);
}, [])

useEffect(() => {
  if(!props.isWeb3)
  props.ConnectWallet();
}, [])


  

  
    	
return(
  <div>
  <div className="columns">
  <div className="column"></div>
  </div>
  <div className="columns">
  <div className="column"></div>   
  </div>
  <div className="columns">
  <div className="column"></div>
  </div>
  <div className="columns">
  <div className="column"></div>   
  </div>
  <div className="columns">
  <div className="column"></div>
  </div>
  <div className="columns">
  <div className="column"></div>   
  </div>
  <div className="box">           
              
              <div className="columns is-centered">  
              
              <div className="column is-6">
                
              <nav className="panel is-light">
              <p class="panel-heading is-centered">
              Verify Account
              </p>
              {
                props.isWeb3?
              <div className="panel-block ">
                Please connect Metamask wallet to continue
              </div>:
              props.allUrlParams.address == props.account? 
              <div className="panel-block ">
              Account verified successfully!
             </div>:
             <div className="panel-block ">
             Please connect the account - {props.allUrlParams.address} 
            </div>

              }
              </nav>
              </div>
              </div>
              </div>
    </div>
                              
)


}

const VerifyLink = React.forwardRef(VerifyLink_);

export default VerifyLink;
