// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState,useEffect} from "react";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
//import "../sass/circularprogressbars.scss";
import { useNavigate } from 'react-router-dom'
//import Web3 from 'web3'
//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

function VerifyLink_(props) {

//const [pageparamsState, setpageparamsState] = useState({ address: "" })

const [addressCheck, setaddressCheck] = useState({result: false})
/*    
const connectWalletandcheck = (address) => {

    console.log("Reached wallet",window.ethereum)
    if (window.ethereum) {
            
            const ethereum = window.ethereum;
            
           let web3 = new Web3(ethereum);
           
        
        ethereum.enable().then((accounts) => {
            let account = accounts[0];
             
            if(account == address)
            {
            setaddressCheck(prevState => {
                return {
                  ...prevState,
                  result: true
                }
              })
            }

        })
    }
}
*/


  useEffect(() => {
    props.urlParser();
    //connectWalletandcheck(props.allUrlParams.address);
}, [])



  

  
    	
return(
            <div>
                <div className="columns">
                <div className="column">
                {props.allUrlParams.address}
                {addressCheck.result}
                </div>
                </div>
                
            </div>                                                
)


}

const VerifyLink = React.forwardRef(VerifyLink_);

export default VerifyLink;
